# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

 

development: 
  adapter: postgresql
  database: todo_development
  password: ~
  pool: 5
  timeout: 5000
  username: inna
production: 
  adapter: postgresql
  database: todo_production
  password: ~
  pool: 5
  timeout: 5000
  username: psql -U inna
  adapter: postgresql
  database: todo_test
  password: ~
  pool: 5
  timeout: 5000
